"""Generic PBR/NPR master material for any MMD character.

The node graph is character independent.  Every texture parameter receives a
typed neutral default, never another slot's authored texture (see
``BuildContext.default_texture``); each per-slot material instance overrides
the texture and scalar parameters.  Optional eye/glass/fringe passes are only
built when the material map declares them.
"""

from __future__ import annotations

import unreal

from ue_context import (
    BuildError,
    connect,
    connect_property,
    constant3,
    expression,
    load_or_create_material,
    safe_set,
    sampler_type,
    scalar,
    smooth_threshold,
    stencil_equal,
    texture_parameter,
    vector,
)


def _configure_surface(material, blend_mode, shading_model, two_sided=True, tangent_space_normal=False):
    for name, value in (
        ("material_domain", unreal.MaterialDomain.MD_SURFACE),
        ("blend_mode", blend_mode),
        ("shading_model", shading_model),
        ("two_sided", two_sided),
        ("used_with_skeletal_mesh", True),
        ("used_with_morph_targets", True),
        ("tangent_space_normal", tangent_space_normal),
    ):
        safe_set(material, name, value)


def create_master(ctx, texture_map):
    """Build the main PBR/NPR master and return it."""
    d = ctx.default_texture
    material = load_or_create_material(ctx.names["master_asset"], ctx.names["material_root"], fresh=True)
    for name, value in (
        ("material_domain", unreal.MaterialDomain.MD_SURFACE),
        ("blend_mode", unreal.BlendMode.BLEND_MASKED),
        ("shading_model", unreal.MaterialShadingModel.MSM_DEFAULT_LIT),
        ("two_sided", True),
        ("opacity_mask_clip_value", 0.12),
        ("used_with_skeletal_mesh", True),
        ("used_with_morph_targets", True),
    ):
        safe_set(material, name, value)

    # ------------------------------------------------------------------
    # PBR + NPR character core
    # ------------------------------------------------------------------
    base = expression(material, unreal.MaterialExpressionTextureSampleParameter2D, -1000, -100)
    safe_set(base, "parameter_name", "BaseColorTexture")
    safe_set(base, "texture", d("base_color"))
    tint = expression(material, unreal.MaterialExpressionVectorParameter, -1000, 100)
    safe_set(tint, "parameter_name", "Tint")
    safe_set(tint, "default_value", unreal.LinearColor(1.0, 1.0, 1.0, 1.0))
    base_mul = expression(material, unreal.MaterialExpressionMultiply, -760, -30)
    connect(base, "RGB", base_mul, "A")
    connect(tint, "", base_mul, "B")

    base_squared = expression(material, unreal.MaterialExpressionMultiply, -520, -30)
    connect(base_mul, "", base_squared, "A")
    connect(base_mul, "", base_squared, "B")
    contrast = expression(material, unreal.MaterialExpressionScalarParameter, -760, 150)
    safe_set(contrast, "parameter_name", "BaseColorContrast")
    safe_set(contrast, "default_value", 0.2)
    base_lerp = expression(material, unreal.MaterialExpressionLinearInterpolate, -260, -30)
    connect(base_mul, "", base_lerp, "A")
    connect(base_squared, "", base_lerp, "B")
    connect(contrast, "", base_lerp, "Alpha")

    # Stocking grazing-angle thickness: tint only the silhouette, never fabric.
    stocking_vertex_normal = expression(material, unreal.MaterialExpressionVertexNormalWS, -220, 120)
    stocking_pixel_normal = expression(material, unreal.MaterialExpressionPixelNormalWS, -220, 40)
    stocking_edge_normal_influence = expression(material, unreal.MaterialExpressionScalarParameter, -220, 320)
    safe_set(stocking_edge_normal_influence, "parameter_name", "StockingEdgeNormalMapInfluence")
    safe_set(stocking_edge_normal_influence, "default_value", 0.25)
    stocking_edge_normal_lerp = expression(material, unreal.MaterialExpressionLinearInterpolate, 0, 60)
    connect(stocking_vertex_normal, "", stocking_edge_normal_lerp, "A")
    connect(stocking_pixel_normal, "", stocking_edge_normal_lerp, "B")
    connect(stocking_edge_normal_influence, "", stocking_edge_normal_lerp, "Alpha")
    stocking_normal = expression(material, unreal.MaterialExpressionNormalize, 210, 60)
    connect(stocking_edge_normal_lerp, "", stocking_normal, "VectorInput")
    stocking_view = expression(material, unreal.MaterialExpressionCameraVectorWS, -220, 220)
    stocking_no_v = expression(material, unreal.MaterialExpressionDotProduct, 20, 150)
    connect(stocking_normal, "", stocking_no_v, "A")
    connect(stocking_view, "", stocking_no_v, "B")
    stocking_no_v_sat = expression(material, unreal.MaterialExpressionSaturate, 230, 150)
    connect(stocking_no_v, "", stocking_no_v_sat, "")
    stocking_grazing = expression(material, unreal.MaterialExpressionOneMinus, 450, 150)
    connect(stocking_no_v_sat, "", stocking_grazing, "")
    stocking_range = expression(material, unreal.MaterialExpressionScalarParameter, 20, 300)
    safe_set(stocking_range, "parameter_name", "StockingEdgeRange")
    safe_set(stocking_range, "default_value", 2.5)
    stocking_curve = expression(material, unreal.MaterialExpressionPower, 680, 150)
    connect(stocking_grazing, "", stocking_curve, "Base")
    connect(stocking_range, "", stocking_curve, "Exp")
    stocking_intensity = expression(material, unreal.MaterialExpressionScalarParameter, 450, 300)
    safe_set(stocking_intensity, "parameter_name", "StockingEdgeIntensity")
    safe_set(stocking_intensity, "default_value", 0.25)
    stocking_weight_raw = expression(material, unreal.MaterialExpressionMultiply, 900, 150)
    connect(stocking_curve, "", stocking_weight_raw, "A")
    connect(stocking_intensity, "", stocking_weight_raw, "B")
    stocking_weight = expression(material, unreal.MaterialExpressionSaturate, 1120, 150)
    connect(stocking_weight_raw, "", stocking_weight, "")
    stocking_edge = expression(material, unreal.MaterialExpressionVectorParameter, 230, 430)
    safe_set(stocking_edge, "parameter_name", "StockingEdgeTint")
    safe_set(stocking_edge, "default_value", unreal.LinearColor(0.52, 0.45, 0.50, 1.0))
    stocking_neutral = constant3(material, (1.0, 1.0, 1.0, 1.0), 900, 360)
    stocking_view_tint = expression(material, unreal.MaterialExpressionLinearInterpolate, 1340, 190)
    connect(stocking_neutral, "", stocking_view_tint, "A")
    connect(stocking_edge, "", stocking_view_tint, "B")
    connect(stocking_weight, "", stocking_view_tint, "Alpha")
    stocking_mode = expression(material, unreal.MaterialExpressionScalarParameter, 450, 430)
    safe_set(stocking_mode, "parameter_name", "StockingMode")
    safe_set(stocking_mode, "default_value", 0.0)
    stocking_selected = expression(material, unreal.MaterialExpressionLinearInterpolate, 1560, 190)
    connect(stocking_neutral, "", stocking_selected, "A")
    connect(stocking_view_tint, "", stocking_selected, "B")
    connect(stocking_mode, "", stocking_selected, "Alpha")
    surface_base = expression(material, unreal.MaterialExpressionMultiply, 1780, 30)
    connect(base_lerp, "", surface_base, "A")
    connect(stocking_selected, "", surface_base, "B")

    pbr_blend = expression(material, unreal.MaterialExpressionScalarParameter, 500, -140)
    safe_set(pbr_blend, "parameter_name", "PBRBlend")
    safe_set(pbr_blend, "default_value", 0.25)
    physical_base = expression(material, unreal.MaterialExpressionMultiply, 760, -80)
    connect(surface_base, "", physical_base, "A")
    connect(pbr_blend, "", physical_base, "B")
    connect_property(physical_base, "", unreal.MaterialProperty.MP_BASE_COLOR)

    alpha_scale = expression(material, unreal.MaterialExpressionScalarParameter, -760, 250)
    safe_set(alpha_scale, "parameter_name", "AlphaScale")
    safe_set(alpha_scale, "default_value", 1.0)
    alpha_mul = expression(material, unreal.MaterialExpressionMultiply, -500, 230)
    connect(base, "A", alpha_mul, "A")
    connect(alpha_scale, "", alpha_mul, "B")
    connect_property(alpha_mul, "", unreal.MaterialProperty.MP_OPACITY_MASK)

    # Normal maps are opt-in; the sampled default never contributes unless the
    # instance raises NormalStrength.
    normal = texture_parameter(material, "NormalTexture", d("normal"), -1000, 420, sampler_type("SAMPLERTYPE_NORMAL"))
    flat_normal = expression(material, unreal.MaterialExpressionVectorParameter, -1000, 600)
    safe_set(flat_normal, "parameter_name", "FlatNormal")
    safe_set(flat_normal, "default_value", unreal.LinearColor(0.0, 0.0, 1.0, 1.0))
    normal_strength = expression(material, unreal.MaterialExpressionScalarParameter, -760, 560)
    safe_set(normal_strength, "parameter_name", "NormalStrength")
    safe_set(normal_strength, "default_value", 0.0)
    normal_lerp = expression(material, unreal.MaterialExpressionLinearInterpolate, -380, 470)
    connect(flat_normal, "", normal_lerp, "A")
    connect(normal, "RGB", normal_lerp, "B")
    connect(normal_strength, "", normal_lerp, "Alpha")
    connect_property(normal_lerp, "", unreal.MaterialProperty.MP_NORMAL)

    rmo = texture_parameter(material, "RMOTexture", d("rmo"), -1000, 820, sampler_type("SAMPLERTYPE_MASKS"))
    use_rmo = expression(material, unreal.MaterialExpressionScalarParameter, -760, 1000)
    safe_set(use_rmo, "parameter_name", "UseRMO")
    safe_set(use_rmo, "default_value", 0.0)
    roughness = expression(material, unreal.MaterialExpressionScalarParameter, -760, 1120)
    safe_set(roughness, "parameter_name", "RoughnessFallback")
    safe_set(roughness, "default_value", 0.55)
    roughness_lerp = expression(material, unreal.MaterialExpressionLinearInterpolate, -360, 980)
    connect(roughness, "", roughness_lerp, "A")
    connect(rmo, "R", roughness_lerp, "B")
    connect(use_rmo, "", roughness_lerp, "Alpha")
    stocking_roughness_scale = expression(material, unreal.MaterialExpressionScalarParameter, -120, 1090)
    safe_set(stocking_roughness_scale, "parameter_name", "StockingRoughnessScale")
    safe_set(stocking_roughness_scale, "default_value", 0.72)
    stocking_roughness_scaled_raw = expression(material, unreal.MaterialExpressionMultiply, 100, 980)
    connect(roughness_lerp, "", stocking_roughness_scaled_raw, "A")
    connect(stocking_roughness_scale, "", stocking_roughness_scaled_raw, "B")
    stocking_roughness_scaled = expression(material, unreal.MaterialExpressionSaturate, 320, 980)
    connect(stocking_roughness_scaled_raw, "", stocking_roughness_scaled, "")
    stocking_roughness_selected = expression(material, unreal.MaterialExpressionLinearInterpolate, 540, 980)
    connect(roughness_lerp, "", stocking_roughness_selected, "A")
    connect(stocking_roughness_scaled, "", stocking_roughness_selected, "B")
    connect(stocking_mode, "", stocking_roughness_selected, "Alpha")
    roughness_scale = scalar(material, "RoughnessMapScale", 1.0, 760, 1100)
    roughness_scaled = expression(material, unreal.MaterialExpressionMultiply, 760, 980)
    connect(stocking_roughness_selected, "", roughness_scaled, "A")
    connect(roughness_scale, "", roughness_scaled, "B")
    roughness_clamped = expression(material, unreal.MaterialExpressionSaturate, 980, 980)
    connect(roughness_scaled, "", roughness_clamped, "")
    connect_property(roughness_clamped, "", unreal.MaterialProperty.MP_ROUGHNESS)

    ao = expression(material, unreal.MaterialExpressionScalarParameter, -760, 1240)
    safe_set(ao, "parameter_name", "AOFallback")
    safe_set(ao, "default_value", 1.0)
    ao_lerp = expression(material, unreal.MaterialExpressionLinearInterpolate, -360, 1190)
    connect(ao, "", ao_lerp, "A")
    connect(rmo, "B", ao_lerp, "B")
    connect(use_rmo, "", ao_lerp, "Alpha")
    connect_property(ao_lerp, "", unreal.MaterialProperty.MP_AMBIENT_OCCLUSION)

    metallic = expression(material, unreal.MaterialExpressionScalarParameter, -760, 1360)
    safe_set(metallic, "parameter_name", "MetallicFallback")
    safe_set(metallic, "default_value", 0.0)
    metallic_map_strength = scalar(material, "RMOMetallicStrength", 1.0, -760, 1450)
    metallic_map_scaled = expression(material, unreal.MaterialExpressionMultiply, -540, 1360)
    connect(rmo, "G", metallic_map_scaled, "A")
    connect(metallic_map_strength, "", metallic_map_scaled, "B")
    metallic_lerp = expression(material, unreal.MaterialExpressionLinearInterpolate, -360, 1360)
    connect(metallic, "", metallic_lerp, "A")
    connect(metallic_map_scaled, "", metallic_lerp, "B")
    connect(use_rmo, "", metallic_lerp, "Alpha")
    connect_property(metallic_lerp, "", unreal.MaterialProperty.MP_METALLIC)

    specular = expression(material, unreal.MaterialExpressionScalarParameter, -760, 1510)
    safe_set(specular, "parameter_name", "Specular")
    safe_set(specular, "default_value", 0.35)
    physical_specular = expression(material, unreal.MaterialExpressionMultiply, -360, 1510)
    connect(specular, "", physical_specular, "A")
    connect(pbr_blend, "", physical_specular, "B")
    connect_property(physical_specular, "", unreal.MaterialProperty.MP_SPECULAR)

    # Anisotropic GGX fibre tangent: reconstruct T' = normalize(T - N dot(T,N))
    # from a character-local vertical direction so both legs share one lobe.
    stocking_anisotropy = expression(material, unreal.MaterialExpressionScalarParameter, -760, 1620)
    safe_set(stocking_anisotropy, "parameter_name", "StockingAnisotropy")
    safe_set(stocking_anisotropy, "default_value", 0.0)
    anisotropy_gated = expression(material, unreal.MaterialExpressionMultiply, -360, 1620)
    connect(stocking_anisotropy, "", anisotropy_gated, "A")
    connect(stocking_mode, "", anisotropy_gated, "B")
    connect_property(anisotropy_gated, "", unreal.MaterialProperty.MP_ANISOTROPY)
    stocking_fibre_local = expression(material, unreal.MaterialExpressionVectorParameter, -760, 1740)
    safe_set(stocking_fibre_local, "parameter_name", "StockingFiberDirectionLocal")
    safe_set(stocking_fibre_local, "default_value", unreal.LinearColor(0.0, 0.0, 1.0, 0.0))
    stocking_fibre_transform = expression(material, unreal.MaterialExpressionTransform, -520, 1740)
    safe_set(stocking_fibre_transform, "transform_source_type", unreal.MaterialVectorCoordTransformSource.TRANSFORMSOURCE_LOCAL)
    safe_set(stocking_fibre_transform, "transform_type", unreal.MaterialVectorCoordTransform.TRANSFORM_WORLD)
    connect(stocking_fibre_local, "RGB", stocking_fibre_transform, "")
    stocking_fibre_world = expression(material, unreal.MaterialExpressionNormalize, -300, 1740)
    connect(stocking_fibre_transform, "", stocking_fibre_world, "VectorInput")
    stocking_fibre_dot_n = expression(material, unreal.MaterialExpressionDotProduct, -80, 1740)
    connect(stocking_fibre_world, "", stocking_fibre_dot_n, "A")
    connect(stocking_pixel_normal, "", stocking_fibre_dot_n, "B")
    stocking_fibre_normal_component = expression(material, unreal.MaterialExpressionMultiply, 140, 1740)
    connect(stocking_pixel_normal, "", stocking_fibre_normal_component, "A")
    connect(stocking_fibre_dot_n, "", stocking_fibre_normal_component, "B")
    stocking_fibre_projected = expression(material, unreal.MaterialExpressionSubtract, 360, 1740)
    connect(stocking_fibre_world, "", stocking_fibre_projected, "A")
    connect(stocking_fibre_normal_component, "", stocking_fibre_projected, "B")
    stocking_fibre_tangent = expression(material, unreal.MaterialExpressionNormalize, 580, 1740)
    connect(stocking_fibre_projected, "", stocking_fibre_tangent, "VectorInput")
    connect_property(stocking_fibre_tangent, "", unreal.MaterialProperty.MP_TANGENT)

    raw_toon_normal = expression(material, unreal.MaterialExpressionVertexNormalWS, -1000, 1570)
    pixel_normal = expression(material, unreal.MaterialExpressionPixelNormalWS, -1000, 1640)
    world_position = expression(material, unreal.MaterialExpressionWorldPosition, -1000, 1470)
    object_position = expression(material, unreal.MaterialExpressionObjectPositionWS, -780, 1470)
    normal_sphere_offset = expression(material, unreal.MaterialExpressionVectorParameter, -780, 1570)
    safe_set(normal_sphere_offset, "parameter_name", "NormalSphereOffset")
    safe_set(normal_sphere_offset, "default_value", unreal.LinearColor(0.0, 0.0, 65.0, 0.0))
    sphere_center = expression(material, unreal.MaterialExpressionAdd, -560, 1470)
    connect(object_position, "", sphere_center, "A")
    connect(normal_sphere_offset, "RGB", sphere_center, "B")
    sphere_delta = expression(material, unreal.MaterialExpressionSubtract, -340, 1470)
    connect(world_position, "", sphere_delta, "A")
    connect(sphere_center, "", sphere_delta, "B")
    sphere_normal = expression(material, unreal.MaterialExpressionNormalize, -120, 1470)
    connect(sphere_delta, "", sphere_normal, "VectorInput")
    normal_warp_strength = expression(material, unreal.MaterialExpressionScalarParameter, -560, 1600)
    safe_set(normal_warp_strength, "parameter_name", "NormalWarpStrength")
    safe_set(normal_warp_strength, "default_value", 0.0)
    toon_normal_blend = expression(material, unreal.MaterialExpressionLinearInterpolate, 100, 1510)
    connect(raw_toon_normal, "", toon_normal_blend, "A")
    connect(sphere_normal, "", toon_normal_blend, "B")
    connect(normal_warp_strength, "", toon_normal_blend, "Alpha")
    macro_toon_normal = expression(material, unreal.MaterialExpressionNormalize, 320, 1510)
    connect(toon_normal_blend, "", macro_toon_normal, "VectorInput")
    npr_normal_map_influence = expression(material, unreal.MaterialExpressionScalarParameter, 100, 1710)
    safe_set(npr_normal_map_influence, "parameter_name", "NPRNormalMapInfluence")
    safe_set(npr_normal_map_influence, "default_value", 0.0)
    toon_normal_detail_blend = expression(material, unreal.MaterialExpressionLinearInterpolate, 540, 1570)
    connect(macro_toon_normal, "", toon_normal_detail_blend, "A")
    connect(pixel_normal, "", toon_normal_detail_blend, "B")
    connect(npr_normal_map_influence, "", toon_normal_detail_blend, "Alpha")
    toon_normal = expression(material, unreal.MaterialExpressionNormalize, 760, 1570)
    connect(toon_normal_detail_blend, "", toon_normal, "VectorInput")
    light_direction = expression(material, unreal.MaterialExpressionSkyAtmosphereLightDirection, -1000, 1780)
    safe_set(light_direction, "light_index", 0)
    light_normalized = expression(material, unreal.MaterialExpressionNormalize, -760, 1780)
    connect(light_direction, "", light_normalized, "VectorInput")
    ndotl = expression(material, unreal.MaterialExpressionDotProduct, -520, 1660)
    connect(toon_normal, "", ndotl, "A")
    connect(light_normalized, "", ndotl, "B")
    ndotl_half = expression(material, unreal.MaterialExpressionMultiply, -300, 1660)
    connect(ndotl, "", ndotl_half, "A")
    safe_set(ndotl_half, "const_b", 0.5)
    half_lambert = expression(material, unreal.MaterialExpressionAdd, -100, 1660)
    connect(ndotl_half, "", half_lambert, "A")
    safe_set(half_lambert, "const_b", 0.5)
    half_lambert_sat = expression(material, unreal.MaterialExpressionSaturate, 100, 1660)
    connect(half_lambert, "", half_lambert_sat, "")

    # Face SDF branch.
    face_mode = expression(material, unreal.MaterialExpressionScalarParameter, -3200, 1500)
    safe_set(face_mode, "parameter_name", "FaceMode")
    safe_set(face_mode, "default_value", 0.0)
    face_forward = expression(material, unreal.MaterialExpressionVectorParameter, -3200, 1620)
    safe_set(face_forward, "parameter_name", "FaceForwardWS")
    safe_set(face_forward, "default_value", unreal.LinearColor(0.0, 1.0, 0.0, 0.0))
    face_forward_world = expression(material, unreal.MaterialExpressionTransform, -3090, 1620)
    safe_set(face_forward_world, "transform_source_type", unreal.MaterialVectorCoordTransformSource.TRANSFORMSOURCE_LOCAL)
    safe_set(face_forward_world, "transform_type", unreal.MaterialVectorCoordTransform.TRANSFORM_WORLD)
    connect(face_forward, "RGB", face_forward_world, "")
    face_forward_normalized = expression(material, unreal.MaterialExpressionNormalize, -2980, 1620)
    connect(face_forward_world, "", face_forward_normalized, "VectorInput")
    face_left = expression(material, unreal.MaterialExpressionVectorParameter, -3200, 1740)
    safe_set(face_left, "parameter_name", "FaceLeftWS")
    safe_set(face_left, "default_value", unreal.LinearColor(-1.0, 0.0, 0.0, 0.0))
    face_left_world = expression(material, unreal.MaterialExpressionTransform, -3090, 1740)
    safe_set(face_left_world, "transform_source_type", unreal.MaterialVectorCoordTransformSource.TRANSFORMSOURCE_LOCAL)
    safe_set(face_left_world, "transform_type", unreal.MaterialVectorCoordTransform.TRANSFORM_WORLD)
    connect(face_left, "RGB", face_left_world, "")
    face_left_normalized = expression(material, unreal.MaterialExpressionNormalize, -2980, 1740)
    connect(face_left_world, "", face_left_normalized, "VectorInput")
    face_forward_dot = expression(material, unreal.MaterialExpressionDotProduct, -2760, 1620)
    connect(light_normalized, "", face_forward_dot, "A")
    connect(face_forward_normalized, "", face_forward_dot, "B")
    face_forward_half = expression(material, unreal.MaterialExpressionMultiply, -2540, 1620)
    connect(face_forward_dot, "", face_forward_half, "A")
    safe_set(face_forward_half, "const_b", 0.5)
    face_forward_remap = expression(material, unreal.MaterialExpressionAdd, -2320, 1620)
    connect(face_forward_half, "", face_forward_remap, "A")
    safe_set(face_forward_remap, "const_b", 0.5)
    face_light_atten = expression(material, unreal.MaterialExpressionOneMinus, -2100, 1620)
    connect(face_forward_remap, "", face_light_atten, "")

    face_uv0 = expression(material, unreal.MaterialExpressionTextureCoordinate, -3420, 1880)
    safe_set(face_uv0, "coordinate_index", 0)
    face_uv1 = expression(material, unreal.MaterialExpressionTextureCoordinate, -3420, 2000)
    safe_set(face_uv1, "coordinate_index", 1)
    face_sdf_use_uv1 = expression(material, unreal.MaterialExpressionScalarParameter, -3420, 2120)
    safe_set(face_sdf_use_uv1, "parameter_name", "FaceSDFUseUV1")
    safe_set(face_sdf_use_uv1, "default_value", 0.0)
    face_sdf_texcoord = expression(material, unreal.MaterialExpressionLinearInterpolate, -3200, 1940)
    connect(face_uv0, "", face_sdf_texcoord, "A")
    connect(face_uv1, "", face_sdf_texcoord, "B")
    connect(face_sdf_use_uv1, "", face_sdf_texcoord, "Alpha")
    face_u = expression(material, unreal.MaterialExpressionComponentMask, -2980, 1880)
    safe_set(face_u, "r", True)
    safe_set(face_u, "g", False)
    safe_set(face_u, "b", False)
    safe_set(face_u, "a", False)
    connect(face_sdf_texcoord, "", face_u, "")
    face_v = expression(material, unreal.MaterialExpressionComponentMask, -2980, 2000)
    safe_set(face_v, "r", False)
    safe_set(face_v, "g", True)
    safe_set(face_v, "b", False)
    safe_set(face_v, "a", False)
    connect(face_sdf_texcoord, "", face_v, "")
    face_v_flipped = expression(material, unreal.MaterialExpressionOneMinus, -2760, 2000)
    connect(face_v, "", face_v_flipped, "")
    face_sdf_flip_v = expression(material, unreal.MaterialExpressionScalarParameter, -2980, 2120)
    safe_set(face_sdf_flip_v, "parameter_name", "FaceSDFFlipV")
    safe_set(face_sdf_flip_v, "default_value", 0.0)
    face_sdf_v = expression(material, unreal.MaterialExpressionLinearInterpolate, -2540, 2000)
    connect(face_v, "", face_sdf_v, "A")
    connect(face_v_flipped, "", face_sdf_v, "B")
    connect(face_sdf_flip_v, "", face_sdf_v, "Alpha")
    face_u_mirror = expression(material, unreal.MaterialExpressionOneMinus, -2760, 1880)
    connect(face_u, "", face_u_mirror, "")
    face_side_dot = expression(material, unreal.MaterialExpressionDotProduct, -2760, 1760)
    connect(light_normalized, "", face_side_dot, "A")
    connect(face_left_normalized, "", face_side_dot, "B")
    face_side_positive = expression(material, unreal.MaterialExpressionSaturate, -2540, 1760)
    connect(face_side_dot, "", face_side_positive, "")
    face_side = expression(material, unreal.MaterialExpressionCeil, -2320, 1760)
    connect(face_side_positive, "", face_side, "")
    face_sdf_u = expression(material, unreal.MaterialExpressionLinearInterpolate, -2540, 1880)
    connect(face_u_mirror, "", face_sdf_u, "A")
    connect(face_u, "", face_sdf_u, "B")
    connect(face_side, "", face_sdf_u, "Alpha")
    face_sdf_uv = expression(material, unreal.MaterialExpressionAppendVector, -2100, 1880)
    connect(face_sdf_u, "", face_sdf_uv, "A")
    connect(face_sdf_v, "", face_sdf_uv, "B")
    face_sdf = texture_parameter(material, "FaceSDFTexture", d("face_sdf"), -1880, 1820, sampler_type("SAMPLERTYPE_MASKS"))
    connect(face_sdf_uv, "", face_sdf, "UVs")
    face_sdf_shadow = expression(material, unreal.MaterialExpressionComponentMask, -1660, 1780)
    safe_set(face_sdf_shadow, "r", True)
    safe_set(face_sdf_shadow, "g", False)
    safe_set(face_sdf_shadow, "b", False)
    safe_set(face_sdf_shadow, "a", False)
    connect(face_sdf, "", face_sdf_shadow, "")
    face_shadow_softness = expression(material, unreal.MaterialExpressionScalarParameter, -1880, 2040)
    safe_set(face_shadow_softness, "parameter_name", "FaceShadowSmoothness")
    safe_set(face_shadow_softness, "default_value", 0.045)
    face_shadow_raw = smooth_threshold(material, face_sdf_shadow, face_light_atten, face_shadow_softness, -1660, 1820)
    face_sdf_controlled_light = expression(material, unreal.MaterialExpressionLinearInterpolate, -100, 1780)
    connect(half_lambert_sat, "", face_sdf_controlled_light, "A")
    connect(face_shadow_raw, "", face_sdf_controlled_light, "B")
    connect(face_sdf, "A", face_sdf_controlled_light, "Alpha")
    selected_diffuse_light = expression(material, unreal.MaterialExpressionLinearInterpolate, 120, 1780)
    connect(half_lambert_sat, "", selected_diffuse_light, "A")
    connect(face_sdf_controlled_light, "", selected_diffuse_light, "B")
    connect(face_mode, "", selected_diffuse_light, "Alpha")

    face_spec_u = expression(material, unreal.MaterialExpressionOneMinus, -2100, 2180)
    connect(face_sdf_u, "", face_spec_u, "")
    face_spec_uv = expression(material, unreal.MaterialExpressionAppendVector, -1880, 2180)
    connect(face_spec_u, "", face_spec_uv, "A")
    connect(face_sdf_v, "", face_spec_uv, "B")
    face_spec_sdf = texture_parameter(material, "FaceSDFTexture", d("face_sdf"), -1660, 2140, sampler_type("SAMPLERTYPE_MASKS"))
    connect(face_spec_uv, "", face_spec_sdf, "UVs")
    face_spec_upper = expression(material, unreal.MaterialExpressionComponentMask, -1440, 2080)
    safe_set(face_spec_upper, "r", False)
    safe_set(face_spec_upper, "g", True)
    safe_set(face_spec_upper, "b", False)
    safe_set(face_spec_upper, "a", False)
    connect(face_spec_sdf, "", face_spec_upper, "")
    face_spec_lower = expression(material, unreal.MaterialExpressionComponentMask, -1440, 2200)
    safe_set(face_spec_lower, "r", False)
    safe_set(face_spec_lower, "g", False)
    safe_set(face_spec_lower, "b", True)
    safe_set(face_spec_lower, "a", False)
    connect(face_spec_sdf, "", face_spec_lower, "")
    face_spec_softness = expression(material, unreal.MaterialExpressionScalarParameter, -1660, 2320)
    safe_set(face_spec_softness, "parameter_name", "FaceSpecSmoothness")
    safe_set(face_spec_softness, "default_value", 0.015)
    face_spec_first = smooth_threshold(material, face_spec_upper, face_light_atten, face_spec_softness, -1440, 2140)
    one_minus_face_atten = expression(material, unreal.MaterialExpressionOneMinus, -1440, 2480)
    connect(face_light_atten, "", one_minus_face_atten, "")
    face_spec_second = smooth_threshold(material, face_spec_lower, one_minus_face_atten, face_spec_softness, -1220, 2480)
    face_spec_area = expression(material, unreal.MaterialExpressionMultiply, 180, 2260)
    connect(face_spec_first, "", face_spec_area, "A")
    connect(face_spec_second, "", face_spec_area, "B")
    face_spec_gated = expression(material, unreal.MaterialExpressionMultiply, 400, 2260)
    connect(face_spec_area, "", face_spec_gated, "A")
    connect(face_mode, "", face_spec_gated, "B")
    face_spec_strength = expression(material, unreal.MaterialExpressionScalarParameter, 400, 2380)
    safe_set(face_spec_strength, "parameter_name", "FaceSDFSpecularStrength")
    safe_set(face_spec_strength, "default_value", 0.0)
    face_spec_scaled = expression(material, unreal.MaterialExpressionMultiply, 620, 2260)
    connect(face_spec_gated, "", face_spec_scaled, "A")
    connect(face_spec_strength, "", face_spec_scaled, "B")
    face_spec_tint = expression(material, unreal.MaterialExpressionVectorParameter, 620, 2380)
    safe_set(face_spec_tint, "parameter_name", "FaceSDFSpecularTint")
    safe_set(face_spec_tint, "default_value", unreal.LinearColor(1.0, 0.72, 0.62, 1.0))
    face_spec_color = expression(material, unreal.MaterialExpressionMultiply, 840, 2260)
    connect(face_spec_scaled, "", face_spec_color, "A")
    connect(face_spec_tint, "", face_spec_color, "B")

    shadow_threshold = expression(material, unreal.MaterialExpressionScalarParameter, -1000, 1940)
    safe_set(shadow_threshold, "parameter_name", "ToonShadowThreshold")
    safe_set(shadow_threshold, "default_value", 0.48)
    band_softness = expression(material, unreal.MaterialExpressionScalarParameter, -1000, 1840)
    safe_set(band_softness, "parameter_name", "ToonBandSoftness")
    safe_set(band_softness, "default_value", 0.10)
    shadow_step = smooth_threshold(material, selected_diffuse_light, shadow_threshold, band_softness, -740, 1940)
    light_threshold = expression(material, unreal.MaterialExpressionScalarParameter, -1000, 2070)
    safe_set(light_threshold, "parameter_name", "ToonLightThreshold")
    safe_set(light_threshold, "default_value", 0.72)
    light_step = smooth_threshold(material, selected_diffuse_light, light_threshold, band_softness, -740, 2170)
    shadow_level = expression(material, unreal.MaterialExpressionScalarParameter, -1000, 2200)
    safe_set(shadow_level, "parameter_name", "ShadowLevel")
    safe_set(shadow_level, "default_value", 0.50)
    mid_level = expression(material, unreal.MaterialExpressionScalarParameter, -1000, 2310)
    safe_set(mid_level, "parameter_name", "MidLevel")
    safe_set(mid_level, "default_value", 0.82)
    shadow_to_mid = expression(material, unreal.MaterialExpressionLinearInterpolate, -80, 1950)
    connect(shadow_level, "", shadow_to_mid, "A")
    connect(mid_level, "", shadow_to_mid, "B")
    connect(shadow_step, "", shadow_to_mid, "Alpha")
    mid_to_light = expression(material, unreal.MaterialExpressionLinearInterpolate, 150, 1950)
    connect(shadow_to_mid, "", mid_to_light, "A")
    safe_set(mid_to_light, "const_b", 1.0)
    connect(light_step, "", mid_to_light, "Alpha")
    continuous_tone = expression(material, unreal.MaterialExpressionLinearInterpolate, 150, 1850)
    connect(shadow_level, "", continuous_tone, "A")
    safe_set(continuous_tone, "const_b", 1.0)
    connect(selected_diffuse_light, "", continuous_tone, "Alpha")
    toon_band_strength = expression(material, unreal.MaterialExpressionScalarParameter, 360, 1850)
    safe_set(toon_band_strength, "parameter_name", "ToonBandStrength")
    safe_set(toon_band_strength, "default_value", 0.15)
    tone_shape = expression(material, unreal.MaterialExpressionLinearInterpolate, 570, 1850)
    connect(continuous_tone, "", tone_shape, "A")
    connect(mid_to_light, "", tone_shape, "B")
    connect(toon_band_strength, "", tone_shape, "Alpha")

    shadow_tint = expression(material, unreal.MaterialExpressionVectorParameter, 150, 2070)
    safe_set(shadow_tint, "parameter_name", "ShadowTint")
    safe_set(shadow_tint, "default_value", unreal.LinearColor(0.72, 0.76, 0.88, 1.0))
    shadow_tint_white = constant3(material, (1.0, 1.0, 1.0, 1.0), 360, 2070)
    shadow_tint_mix = expression(material, unreal.MaterialExpressionLinearInterpolate, 560, 1970)
    connect(shadow_tint, "", shadow_tint_mix, "A")
    connect(shadow_tint_white, "", shadow_tint_mix, "B")
    connect(shadow_step, "", shadow_tint_mix, "Alpha")

    inverse_light = expression(material, unreal.MaterialExpressionOneMinus, -100, 2200)
    connect(selected_diffuse_light, "", inverse_light, "")
    ramp_x = expression(material, unreal.MaterialExpressionConstant, -320, 2300)
    safe_set(ramp_x, "r", 0.5)
    ramp_uv = expression(material, unreal.MaterialExpressionAppendVector, 100, 2200)
    connect(ramp_x, "", ramp_uv, "A")
    connect(inverse_light, "", ramp_uv, "B")
    toon_ramp = texture_parameter(material, "ToonRampTexture", d("toon_ramp"), 330, 2180)
    connect(ramp_uv, "", toon_ramp, "UVs")
    ramp_strength = expression(material, unreal.MaterialExpressionScalarParameter, 330, 2340)
    safe_set(ramp_strength, "parameter_name", "ToonRampStrength")
    safe_set(ramp_strength, "default_value", 0.18)
    ramp_white = constant3(material, (1.0, 1.0, 1.0, 1.0), 330, 2440)
    ramp_mix = expression(material, unreal.MaterialExpressionLinearInterpolate, 560, 2220)
    connect(ramp_white, "", ramp_mix, "A")
    connect(toon_ramp, "RGB", ramp_mix, "B")
    connect(ramp_strength, "", ramp_mix, "Alpha")
    tone_with_ramp = expression(material, unreal.MaterialExpressionMultiply, 780, 2040)
    connect(tone_shape, "", tone_with_ramp, "A")
    connect(ramp_mix, "", tone_with_ramp, "B")
    tone_tinted = expression(material, unreal.MaterialExpressionMultiply, 820, 2140)
    connect(tone_with_ramp, "", tone_tinted, "A")
    connect(shadow_tint_mix, "", tone_tinted, "B")

    ao_influence = expression(material, unreal.MaterialExpressionScalarParameter, 330, 2580)
    safe_set(ao_influence, "parameter_name", "AOInfluence")
    safe_set(ao_influence, "default_value", 0.35)
    ao_one = expression(material, unreal.MaterialExpressionConstant, 330, 2690)
    safe_set(ao_one, "r", 1.0)
    ao_mix = expression(material, unreal.MaterialExpressionLinearInterpolate, 560, 2580)
    connect(ao_one, "", ao_mix, "A")
    connect(ao_lerp, "", ao_mix, "B")
    connect(ao_influence, "", ao_mix, "Alpha")
    lit_base = expression(material, unreal.MaterialExpressionMultiply, 1020, 2040)
    connect(surface_base, "", lit_base, "A")
    connect(tone_tinted, "", lit_base, "B")
    lit_base_ao = expression(material, unreal.MaterialExpressionMultiply, 1250, 2040)
    connect(lit_base, "", lit_base_ao, "A")
    connect(ao_mix, "", lit_base_ao, "B")

    camera_vector = expression(material, unreal.MaterialExpressionCameraVectorWS, -1000, 2860)
    half_vector_add = expression(material, unreal.MaterialExpressionAdd, -760, 2860)
    connect(camera_vector, "", half_vector_add, "A")
    connect(light_normalized, "", half_vector_add, "B")
    half_vector = expression(material, unreal.MaterialExpressionNormalize, -540, 2860)
    connect(half_vector_add, "", half_vector, "VectorInput")
    ndoth = expression(material, unreal.MaterialExpressionDotProduct, -320, 2780)
    connect(pixel_normal, "", ndoth, "A")
    connect(half_vector, "", ndoth, "B")
    ndoth_sat = expression(material, unreal.MaterialExpressionSaturate, -100, 2780)
    connect(ndoth, "", ndoth_sat, "")
    spec_power = expression(material, unreal.MaterialExpressionScalarParameter, -320, 3000)
    safe_set(spec_power, "parameter_name", "SpecularPower")
    safe_set(spec_power, "default_value", 48.0)
    regular_spec = expression(material, unreal.MaterialExpressionPower, 120, 2780)
    connect(ndoth_sat, "", regular_spec, "Base")
    connect(spec_power, "", regular_spec, "Exp")
    inv_roughness = expression(material, unreal.MaterialExpressionOneMinus, 120, 2940)
    connect(roughness_lerp, "", inv_roughness, "")
    regular_spec_rough = expression(material, unreal.MaterialExpressionMultiply, 350, 2780)
    connect(regular_spec, "", regular_spec_rough, "A")
    connect(inv_roughness, "", regular_spec_rough, "B")
    regular_spec_strength = expression(material, unreal.MaterialExpressionMultiply, 570, 2780)
    connect(regular_spec_rough, "", regular_spec_strength, "A")
    connect(specular, "", regular_spec_strength, "B")

    detail_mask = texture_parameter(material, "DetailMaskTexture", d("spec_mask"), -1000, 1660, sampler_type("SAMPLERTYPE_MASKS"))
    hair_uv1 = expression(material, unreal.MaterialExpressionTextureCoordinate, -1000, 3220)
    safe_set(hair_uv1, "coordinate_index", 1)
    camera_y = expression(material, unreal.MaterialExpressionComponentMask, -780, 3220)
    safe_set(camera_y, "r", False)
    safe_set(camera_y, "g", True)
    safe_set(camera_y, "b", False)
    safe_set(camera_y, "a", False)
    connect(camera_vector, "", camera_y, "")
    hair_offset_speed = expression(material, unreal.MaterialExpressionScalarParameter, -780, 3360)
    safe_set(hair_offset_speed, "parameter_name", "HairSpecOffsetSpeed")
    safe_set(hair_offset_speed, "default_value", 0.08)
    hair_view_offset = expression(material, unreal.MaterialExpressionMultiply, -560, 3220)
    connect(camera_y, "", hair_view_offset, "A")
    connect(hair_offset_speed, "", hair_view_offset, "B")
    hair_view_offset_negative = expression(material, unreal.MaterialExpressionMultiply, -340, 3220)
    connect(hair_view_offset, "", hair_view_offset_negative, "A")
    safe_set(hair_view_offset_negative, "const_b", -1.0)
    hair_offset_bias = expression(material, unreal.MaterialExpressionScalarParameter, -560, 3360)
    safe_set(hair_offset_bias, "parameter_name", "HairSpecOffset")
    safe_set(hair_offset_bias, "default_value", 0.0)
    hair_offset_v = expression(material, unreal.MaterialExpressionAdd, -120, 3220)
    connect(hair_view_offset_negative, "", hair_offset_v, "A")
    connect(hair_offset_bias, "", hair_offset_v, "B")
    hair_offset_u = expression(material, unreal.MaterialExpressionConstant, -120, 3340)
    safe_set(hair_offset_u, "r", 0.0)
    hair_uv_offset = expression(material, unreal.MaterialExpressionAppendVector, 100, 3220)
    connect(hair_offset_u, "", hair_uv_offset, "A")
    connect(hair_offset_v, "", hair_uv_offset, "B")
    hair_uv_shifted = expression(material, unreal.MaterialExpressionAdd, 320, 3220)
    connect(hair_uv1, "", hair_uv_shifted, "A")
    connect(hair_uv_offset, "", hair_uv_shifted, "B")
    connect(hair_uv_shifted, "", detail_mask, "UVs")
    highlight_strength = expression(material, unreal.MaterialExpressionScalarParameter, -760, 1810)
    safe_set(highlight_strength, "parameter_name", "HairHighlightStrength")
    safe_set(highlight_strength, "default_value", 0.0)
    highlight_tint = expression(material, unreal.MaterialExpressionVectorParameter, -760, 1930)
    safe_set(highlight_tint, "parameter_name", "HairHighlightTint")
    safe_set(highlight_tint, "default_value", unreal.LinearColor(0.9, 0.95, 1.0, 1.0))
    hair_power = expression(material, unreal.MaterialExpressionScalarParameter, -100, 3370)
    safe_set(hair_power, "parameter_name", "HairSpecPower")
    safe_set(hair_power, "default_value", 8.0)
    hair_lobe = expression(material, unreal.MaterialExpressionPower, 350, 3210)
    connect(ndoth_sat, "", hair_lobe, "Base")
    connect(hair_power, "", hair_lobe, "Exp")
    hair_spec_min = expression(material, unreal.MaterialExpressionScalarParameter, 350, 3370)
    safe_set(hair_spec_min, "parameter_name", "HairSpecMinIntensity")
    safe_set(hair_spec_min, "default_value", 0.08)
    hair_lobe_biased = expression(material, unreal.MaterialExpressionAdd, 570, 3210)
    connect(hair_lobe, "", hair_lobe_biased, "A")
    connect(hair_spec_min, "", hair_lobe_biased, "B")
    hair_spec_intensity = expression(material, unreal.MaterialExpressionSaturate, 790, 3210)
    connect(hair_lobe_biased, "", hair_spec_intensity, "")
    hair_masked = expression(material, unreal.MaterialExpressionMultiply, 1010, 3210)
    connect(hair_spec_intensity, "", hair_masked, "A")
    connect(detail_mask, "RGB", hair_masked, "B")
    hair_spec_strength = expression(material, unreal.MaterialExpressionMultiply, 1230, 3210)
    connect(hair_masked, "", hair_spec_strength, "A")
    connect(highlight_strength, "", hair_spec_strength, "B")
    hair_mode = expression(material, unreal.MaterialExpressionScalarParameter, 570, 3370)
    safe_set(hair_mode, "parameter_name", "HairMode")
    safe_set(hair_mode, "default_value", 0.0)
    selected_spec = expression(material, unreal.MaterialExpressionLinearInterpolate, 1450, 2860)
    connect(regular_spec_strength, "", selected_spec, "A")
    connect(hair_spec_strength, "", selected_spec, "B")
    connect(hair_mode, "", selected_spec, "Alpha")
    npr_specular_strength = expression(material, unreal.MaterialExpressionScalarParameter, 980, 3010)
    safe_set(npr_specular_strength, "parameter_name", "NPRSpecularStrength")
    safe_set(npr_specular_strength, "default_value", 0.0)
    selected_spec_scaled = expression(material, unreal.MaterialExpressionMultiply, 1160, 2860)
    connect(selected_spec, "", selected_spec_scaled, "A")
    connect(npr_specular_strength, "", selected_spec_scaled, "B")
    spec_light_gate = expression(material, unreal.MaterialExpressionMultiply, 1160, 2970)
    connect(selected_spec_scaled, "", spec_light_gate, "A")
    connect(selected_diffuse_light, "", spec_light_gate, "B")
    specular_color = expression(material, unreal.MaterialExpressionMultiply, 1250, 2860)
    connect(spec_light_gate, "", specular_color, "A")
    connect(highlight_tint, "", specular_color, "B")

    ambient_lift = expression(material, unreal.MaterialExpressionScalarParameter, -760, 2070)
    safe_set(ambient_lift, "parameter_name", "AmbientLift")
    safe_set(ambient_lift, "default_value", 0.015)
    ambient_mul = expression(material, unreal.MaterialExpressionMultiply, 1020, 3500)
    connect(surface_base, "", ambient_mul, "A")
    connect(ambient_lift, "", ambient_mul, "B")
    eye_glow = expression(material, unreal.MaterialExpressionScalarParameter, -760, 2190)
    safe_set(eye_glow, "parameter_name", "EyeGlow")
    safe_set(eye_glow, "default_value", 0.0)
    eye_mul = expression(material, unreal.MaterialExpressionMultiply, 1020, 3620)
    connect(surface_base, "", eye_mul, "A")
    connect(eye_glow, "", eye_mul, "B")

    fresnel = expression(material, unreal.MaterialExpressionFresnel, 350, 3740)
    rim_threshold = expression(material, unreal.MaterialExpressionScalarParameter, 350, 3880)
    safe_set(rim_threshold, "parameter_name", "RimThreshold")
    safe_set(rim_threshold, "default_value", 0.78)
    rim_delta = expression(material, unreal.MaterialExpressionSubtract, 570, 3740)
    connect(fresnel, "", rim_delta, "A")
    connect(rim_threshold, "", rim_delta, "B")
    rim_ceil = expression(material, unreal.MaterialExpressionCeil, 790, 3740)
    connect(rim_delta, "", rim_ceil, "")
    rim_step = expression(material, unreal.MaterialExpressionSaturate, 1010, 3740)
    connect(rim_ceil, "", rim_step, "")
    rim_strength = expression(material, unreal.MaterialExpressionScalarParameter, -760, 2470)
    safe_set(rim_strength, "parameter_name", "RimStrength")
    safe_set(rim_strength, "default_value", 0.02)
    rim_tint = expression(material, unreal.MaterialExpressionVectorParameter, -760, 2590)
    safe_set(rim_tint, "parameter_name", "RimTint")
    safe_set(rim_tint, "default_value", unreal.LinearColor(0.5, 0.65, 0.9, 1.0))
    rim_strength_mul = expression(material, unreal.MaterialExpressionMultiply, 1230, 3740)
    connect(rim_step, "", rim_strength_mul, "A")
    connect(rim_strength, "", rim_strength_mul, "B")
    rim_color_mul = expression(material, unreal.MaterialExpressionMultiply, 1450, 3740)
    connect(rim_strength_mul, "", rim_color_mul, "A")
    connect(rim_tint, "", rim_color_mul, "B")

    diffuse_spec_add = expression(material, unreal.MaterialExpressionAdd, 1480, 2500)
    connect(lit_base_ao, "", diffuse_spec_add, "A")
    connect(specular_color, "", diffuse_spec_add, "B")
    diffuse_face_spec_add = expression(material, unreal.MaterialExpressionAdd, 1700, 2500)
    connect(diffuse_spec_add, "", diffuse_face_spec_add, "A")
    connect(face_spec_color, "", diffuse_face_spec_add, "B")
    ambient_eye_add = expression(material, unreal.MaterialExpressionAdd, 1480, 3380)
    connect(ambient_mul, "", ambient_eye_add, "A")
    connect(eye_mul, "", ambient_eye_add, "B")
    lit_accents_add = expression(material, unreal.MaterialExpressionAdd, 1720, 2700)
    connect(diffuse_face_spec_add, "", lit_accents_add, "A")
    connect(ambient_eye_add, "", lit_accents_add, "B")
    final_emissive_add = expression(material, unreal.MaterialExpressionAdd, 1940, 2860)
    connect(lit_accents_add, "", final_emissive_add, "A")
    connect(rim_color_mul, "", final_emissive_add, "B")
    output_gain = expression(material, unreal.MaterialExpressionScalarParameter, 1940, 3020)
    safe_set(output_gain, "parameter_name", "OutputGain")
    safe_set(output_gain, "default_value", 0.82)
    output_scaled = expression(material, unreal.MaterialExpressionMultiply, 2170, 2860)
    connect(final_emissive_add, "", output_scaled, "A")
    connect(output_gain, "", output_scaled, "B")
    npr_weight = expression(material, unreal.MaterialExpressionOneMinus, 2170, 3020)
    connect(pbr_blend, "", npr_weight, "")
    output_hybrid = expression(material, unreal.MaterialExpressionMultiply, 2390, 2860)
    connect(output_scaled, "", output_hybrid, "A")
    connect(npr_weight, "", output_hybrid, "B")

    # Material-local ambient fill for dark PBR garments.  The mask follows the
    # same primary light as the toon diffuse, but fades to zero on lit normals.
    # Default strength is zero so existing characters and slots are unchanged.
    pbr_shadow_lift = scalar(material, "PBRShadowLift", 0.0, 2170, 3920)
    pbr_shadow_mask = expression(material, unreal.MaterialExpressionOneMinus, 2170, 3800)
    connect(shadow_step, "", pbr_shadow_mask, "")
    pbr_shadow_color = expression(material, unreal.MaterialExpressionMultiply, 2390, 3800)
    connect(surface_base, "", pbr_shadow_color, "A")
    connect(pbr_shadow_mask, "", pbr_shadow_color, "B")
    pbr_shadow_scaled = expression(material, unreal.MaterialExpressionMultiply, 2610, 3800)
    connect(pbr_shadow_color, "", pbr_shadow_scaled, "A")
    connect(pbr_shadow_lift, "", pbr_shadow_scaled, "B")
    pbr_shadow_gated = expression(material, unreal.MaterialExpressionMultiply, 2830, 3800)
    connect(pbr_shadow_scaled, "", pbr_shadow_gated, "A")
    connect(pbr_blend, "", pbr_shadow_gated, "B")
    output_with_pbr_shadow_lift = expression(material, unreal.MaterialExpressionAdd, 2610, 2700)
    connect(output_hybrid, "", output_with_pbr_shadow_lift, "A")
    connect(pbr_shadow_gated, "", output_with_pbr_shadow_lift, "B")
    output_clamped = expression(material, unreal.MaterialExpressionSaturate, 2610, 2860)
    connect(output_with_pbr_shadow_lift, "", output_clamped, "")

    debug_r_weight = expression(material, unreal.MaterialExpressionScalarParameter, 1940, 3140)
    safe_set(debug_r_weight, "parameter_name", "FaceSDFDebugR")
    safe_set(debug_r_weight, "default_value", 0.0)
    debug_a_weight = expression(material, unreal.MaterialExpressionScalarParameter, 1940, 3260)
    safe_set(debug_a_weight, "parameter_name", "FaceSDFDebugA")
    safe_set(debug_a_weight, "default_value", 0.0)
    debug_shadow_weight = expression(material, unreal.MaterialExpressionScalarParameter, 1940, 3380)
    safe_set(debug_shadow_weight, "parameter_name", "FaceSDFDebugShadow")
    safe_set(debug_shadow_weight, "default_value", 0.0)
    debug_r = expression(material, unreal.MaterialExpressionMultiply, 2170, 3140)
    connect(face_sdf_shadow, "", debug_r, "A")
    connect(debug_r_weight, "", debug_r, "B")
    debug_a = expression(material, unreal.MaterialExpressionMultiply, 2170, 3260)
    connect(face_sdf, "A", debug_a, "A")
    connect(debug_a_weight, "", debug_a, "B")
    debug_shadow = expression(material, unreal.MaterialExpressionMultiply, 2170, 3380)
    connect(face_shadow_raw, "", debug_shadow, "A")
    connect(debug_shadow_weight, "", debug_shadow, "B")
    debug_ra = expression(material, unreal.MaterialExpressionAdd, 2390, 3200)
    connect(debug_r, "", debug_ra, "A")
    connect(debug_a, "", debug_ra, "B")
    debug_value_sum = expression(material, unreal.MaterialExpressionAdd, 2610, 3260)
    connect(debug_ra, "", debug_value_sum, "A")
    connect(debug_shadow, "", debug_value_sum, "B")
    debug_value = expression(material, unreal.MaterialExpressionSaturate, 2830, 3260)
    connect(debug_value_sum, "", debug_value, "")
    debug_weight_ra = expression(material, unreal.MaterialExpressionAdd, 2390, 3440)
    connect(debug_r_weight, "", debug_weight_ra, "A")
    connect(debug_a_weight, "", debug_weight_ra, "B")
    debug_weight_sum = expression(material, unreal.MaterialExpressionAdd, 2610, 3440)
    connect(debug_weight_ra, "", debug_weight_sum, "A")
    connect(debug_shadow_weight, "", debug_weight_sum, "B")
    debug_weight = expression(material, unreal.MaterialExpressionSaturate, 2830, 3440)
    connect(debug_weight_sum, "", debug_weight, "")
    output_with_debug = expression(material, unreal.MaterialExpressionLinearInterpolate, 3050, 2960)
    connect(output_clamped, "", output_with_debug, "A")
    connect(debug_value, "", output_with_debug, "B")
    connect(debug_weight, "", output_with_debug, "Alpha")
    connect_property(output_with_debug, "", unreal.MaterialProperty.MP_EMISSIVE_COLOR)

    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
    return material


def create_eye_blend(ctx, asset_name: str, blend_mode):
    """Unlit additive/multiply overlay used by layered eye geometry."""
    material = load_or_create_material(asset_name, ctx.names["material_root"], fresh=True)
    _configure_surface(material, blend_mode, unreal.MaterialShadingModel.MSM_UNLIT, two_sided=True)
    texture = texture_parameter(material, "BaseColorTexture", ctx.default_texture("base_color"), -720, -80)
    tint = vector(material, "Tint", (1.0, 1.0, 1.0, 1.0), -720, 100)
    color = expression(material, unreal.MaterialExpressionMultiply, -460, -40)
    connect(texture, "RGB", color, "A")
    connect(tint, "", color, "B")
    strength = scalar(material, "EyeOverlayStrength", 1.0, -460, 120)
    output = expression(material, unreal.MaterialExpressionMultiply, -220, -40)
    connect(color, "", output, "A")
    connect(strength, "", output, "B")
    connect_property(output, "", unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    alpha_scale = scalar(material, "AlphaScale", 1.0, -460, 260)
    opacity = expression(material, unreal.MaterialExpressionMultiply, -220, 220)
    connect(texture, "A", opacity, "A")
    connect(alpha_scale, "", opacity, "B")
    connect_property(opacity, "", unreal.MaterialProperty.MP_OPACITY)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
    return material


def create_empty(ctx, asset_name: str, blend_mode, shading_model):
    material = load_or_create_material(asset_name, ctx.names["material_root"], fresh=True)
    _configure_surface(material, blend_mode, shading_model, two_sided=True)
    return material


def create_invisible(ctx):
    material = create_empty(ctx, ctx.names["invisible_asset"], unreal.BlendMode.BLEND_MASKED, unreal.MaterialShadingModel.MSM_UNLIT)
    zero = expression(material, unreal.MaterialExpressionConstant, -200, 0)
    safe_set(zero, "r", 0.0)
    connect_property(zero, "", unreal.MaterialProperty.MP_OPACITY_MASK)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
    return material


def create_glass(ctx):
    material = load_or_create_material(ctx.names["glass_asset"], ctx.names["material_root"], fresh=True)
    _configure_surface(material, unreal.BlendMode.BLEND_TRANSLUCENT, unreal.MaterialShadingModel.MSM_DEFAULT_LIT, two_sided=True)
    texture = texture_parameter(material, "BaseColorTexture", ctx.default_texture("base_color"), -760, -80)
    tint = vector(material, "Tint", (0.18, 0.23, 0.24, 1.0), -760, 100)
    color = expression(material, unreal.MaterialExpressionMultiply, -520, -80)
    connect(texture, "RGB", color, "A")
    connect(tint, "RGB", color, "B")
    connect_property(color, "", unreal.MaterialProperty.MP_BASE_COLOR)
    strength = scalar(material, "GlassOpacity", 0.18, -520, 220)
    opacity = expression(material, unreal.MaterialExpressionMultiply, -280, 40)
    connect(texture, "A", opacity, "A")
    connect(strength, "", opacity, "B")
    connect_property(opacity, "", unreal.MaterialProperty.MP_OPACITY)
    roughness = scalar(material, "RoughnessFallback", 0.08, -520, 360)
    connect_property(roughness, "", unreal.MaterialProperty.MP_ROUGHNESS)
    specular = scalar(material, "Specular", 0.72, -520, 480)
    connect_property(specular, "", unreal.MaterialProperty.MP_SPECULAR)
    unreal.MaterialEditingLibrary.recompile_material(material)
    unreal.EditorAssetLibrary.save_loaded_asset(material)
    return material


def create_bang_passes(ctx, hair_base_texture, hair_spec_texture, bang_opacity=0.82, eye_opacity=0.22):
    """Stencil-aware fringe passes.  Operate on the shared mesh; no copy."""
    if hair_base_texture is None or hair_spec_texture is None:
        raise BuildError("bang passes require a hair base texture and a UV1 specular mask")

    invisible = create_invisible(ctx)

    overlay = create_empty(ctx, ctx.names["bang_overlay_asset"], unreal.BlendMode.BLEND_TRANSLUCENT, unreal.MaterialShadingModel.MSM_UNLIT)
    base = texture_parameter(overlay, "BaseColorTexture", hair_base_texture, -1600, -120)
    tint = vector(overlay, "Tint", (1.0, 0.97, 0.98, 1.0), -1600, 40)
    tinted = expression(overlay, unreal.MaterialExpressionMultiply, -1380, -80)
    connect(base, "RGB", tinted, "A")
    connect(tint, "RGB", tinted, "B")
    light = vector(overlay, "LightDirection", (-0.35, 0.50, 0.78, 0.0), -1600, 240)
    light_n = expression(overlay, unreal.MaterialExpressionNormalize, -1380, 240)
    connect(light, "RGB", light_n, "VectorInput")
    normal = expression(overlay, unreal.MaterialExpressionPixelNormalWS, -1600, 360)
    ndotl = expression(overlay, unreal.MaterialExpressionDotProduct, -1160, 280)
    connect(normal, "", ndotl, "A")
    connect(light_n, "", ndotl, "B")
    ndotl_sat = expression(overlay, unreal.MaterialExpressionSaturate, -940, 280)
    connect(ndotl, "", ndotl_sat, "")
    shadow_softness = scalar(overlay, "BangDiffuseSoftness", 0.16, -1160, 420)
    shadow_threshold = scalar(overlay, "BangDiffuseThreshold", 0.44, -940, 420)
    lit_weight = smooth_threshold(overlay, ndotl_sat, shadow_threshold, shadow_softness, -720, 280)
    shadow_tint = vector(overlay, "BangShadowTint", (0.58, 0.48, 0.53, 1.0), -720, 440)
    one = constant3(overlay, (1.0, 1.0, 1.0, 1.0), -500, 440)
    diffuse_tone = expression(overlay, unreal.MaterialExpressionLinearInterpolate, -280, 280)
    connect(shadow_tint, "RGB", diffuse_tone, "A")
    connect(one, "", diffuse_tone, "B")
    connect(lit_weight, "", diffuse_tone, "Alpha")
    diffuse = expression(overlay, unreal.MaterialExpressionMultiply, -60, 140)
    connect(tinted, "", diffuse, "A")
    connect(diffuse_tone, "", diffuse, "B")
    camera = expression(overlay, unreal.MaterialExpressionCameraVectorWS, -1600, 660)
    half_add = expression(overlay, unreal.MaterialExpressionAdd, -1380, 660)
    connect(camera, "", half_add, "A")
    connect(light_n, "", half_add, "B")
    half_vector = expression(overlay, unreal.MaterialExpressionNormalize, -1160, 660)
    connect(half_add, "", half_vector, "VectorInput")
    ndoth = expression(overlay, unreal.MaterialExpressionDotProduct, -940, 660)
    connect(normal, "", ndoth, "A")
    connect(half_vector, "", ndoth, "B")
    ndoth_sat = expression(overlay, unreal.MaterialExpressionSaturate, -720, 660)
    connect(ndoth, "", ndoth_sat, "")
    spec_power = scalar(overlay, "HairSpecPower", 6.0, -940, 800)
    spec_lobe = expression(overlay, unreal.MaterialExpressionPower, -500, 660)
    connect(ndoth_sat, "", spec_lobe, "Base")
    connect(spec_power, "", spec_lobe, "Exp")
    spec_min = scalar(overlay, "HairSpecMinIntensity", 0.1, -500, 800)
    spec_biased = expression(overlay, unreal.MaterialExpressionAdd, -280, 660)
    connect(spec_lobe, "", spec_biased, "A")
    connect(spec_min, "", spec_biased, "B")
    spec_intensity = expression(overlay, unreal.MaterialExpressionSaturate, -60, 660)
    connect(spec_biased, "", spec_intensity, "")
    uv1 = expression(overlay, unreal.MaterialExpressionTextureCoordinate, -1600, 980)
    safe_set(uv1, "coordinate_index", 1)
    camera_y = expression(overlay, unreal.MaterialExpressionComponentMask, -1380, 980)
    safe_set(camera_y, "r", False)
    safe_set(camera_y, "g", True)
    safe_set(camera_y, "b", False)
    safe_set(camera_y, "a", False)
    connect(camera, "", camera_y, "")
    offset_speed = scalar(overlay, "HairSpecOffsetSpeed", 0.05, -1380, 1120)
    view_offset = expression(overlay, unreal.MaterialExpressionMultiply, -1160, 980)
    connect(camera_y, "", view_offset, "A")
    connect(offset_speed, "", view_offset, "B")
    view_offset_negative = expression(overlay, unreal.MaterialExpressionMultiply, -940, 980)
    connect(view_offset, "", view_offset_negative, "A")
    safe_set(view_offset_negative, "const_b", -1.0)
    offset_bias = scalar(overlay, "HairSpecOffset", 0.0, -1160, 1120)
    offset_v = expression(overlay, unreal.MaterialExpressionAdd, -720, 980)
    connect(view_offset_negative, "", offset_v, "A")
    connect(offset_bias, "", offset_v, "B")
    offset_u = expression(overlay, unreal.MaterialExpressionConstant, -720, 1120)
    safe_set(offset_u, "r", 0.0)
    uv_offset = expression(overlay, unreal.MaterialExpressionAppendVector, -500, 980)
    connect(offset_u, "", uv_offset, "A")
    connect(offset_v, "", uv_offset, "B")
    shifted_uv = expression(overlay, unreal.MaterialExpressionAdd, -280, 980)
    connect(uv1, "", shifted_uv, "A")
    connect(uv_offset, "", shifted_uv, "B")
    spec_map = texture_parameter(overlay, "DetailMaskTexture", hair_spec_texture, -60, 940, sampler_type("SAMPLERTYPE_MASKS"))
    connect(shifted_uv, "", spec_map, "UVs")
    spec_masked = expression(overlay, unreal.MaterialExpressionMultiply, 180, 720)
    connect(spec_map, "RGB", spec_masked, "A")
    connect(spec_intensity, "", spec_masked, "B")
    spec_strength = scalar(overlay, "HairHighlightStrength", 0.11, 180, 900)
    spec_scaled = expression(overlay, unreal.MaterialExpressionMultiply, 400, 720)
    connect(spec_masked, "", spec_scaled, "A")
    connect(spec_strength, "", spec_scaled, "B")
    spec_tint = vector(overlay, "HairHighlightTint", (0.95, 0.82, 0.86, 1.0), 400, 900)
    spec_color = expression(overlay, unreal.MaterialExpressionMultiply, 620, 720)
    connect(spec_scaled, "", spec_color, "A")
    connect(spec_tint, "RGB", spec_color, "B")
    final_color = expression(overlay, unreal.MaterialExpressionAdd, 840, 360)
    connect(diffuse, "", final_color, "A")
    connect(spec_color, "", final_color, "B")
    connect_property(final_color, "", unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    eye_stencil = stencil_equal(overlay, 2.0, -1600, 1320)
    opaque_alpha = scalar(overlay, "BangOpacity", bang_opacity, -280, 1480)
    eye_alpha = scalar(overlay, "BangEyeOpacity", eye_opacity, -60, 1480)
    stencil_alpha = expression(overlay, unreal.MaterialExpressionLinearInterpolate, 180, 1320)
    connect(opaque_alpha, "", stencil_alpha, "A")
    connect(eye_alpha, "", stencil_alpha, "B")
    connect(eye_stencil, "", stencil_alpha, "Alpha")
    opacity = expression(overlay, unreal.MaterialExpressionMultiply, 400, 1320)
    connect(base, "A", opacity, "A")
    connect(stencil_alpha, "", opacity, "B")
    connect_property(opacity, "", unreal.MaterialProperty.MP_OPACITY)
    unreal.MaterialEditingLibrary.recompile_material(overlay)
    unreal.EditorAssetLibrary.save_loaded_asset(overlay)

    shadow = create_empty(ctx, ctx.names["bang_shadow_asset"], unreal.BlendMode.BLEND_TRANSLUCENT, unreal.MaterialShadingModel.MSM_UNLIT)
    shadow_base = texture_parameter(shadow, "BaseColorTexture", hair_base_texture, -1500, -140)
    shadow_light = vector(shadow, "LightDirection", (-0.35, 0.50, 0.78, 0.0), -1500, 160)
    shadow_light_n = expression(shadow, unreal.MaterialExpressionNormalize, -1280, 160)
    connect(shadow_light, "RGB", shadow_light_n, "VectorInput")
    world_to_view = expression(shadow, unreal.MaterialExpressionTransform, -1060, 160)
    safe_set(world_to_view, "transform_source_type", unreal.MaterialVectorCoordTransformSource.TRANSFORMSOURCE_WORLD)
    safe_set(world_to_view, "transform_type", unreal.MaterialVectorCoordTransform.TRANSFORM_VIEW)
    connect(shadow_light_n, "", world_to_view, "")
    light_xy = expression(shadow, unreal.MaterialExpressionComponentMask, -840, 160)
    safe_set(light_xy, "r", True)
    safe_set(light_xy, "g", True)
    safe_set(light_xy, "b", False)
    safe_set(light_xy, "a", False)
    connect(world_to_view, "", light_xy, "")
    zero_z = expression(shadow, unreal.MaterialExpressionConstant, -840, 300)
    safe_set(zero_z, "r", 0.0)
    light_view_xy = expression(shadow, unreal.MaterialExpressionAppendVector, -620, 160)
    connect(light_xy, "", light_view_xy, "A")
    connect(zero_z, "", light_view_xy, "B")
    view_to_world = expression(shadow, unreal.MaterialExpressionTransform, -400, 160)
    safe_set(view_to_world, "transform_source_type", unreal.MaterialVectorCoordTransformSource.TRANSFORMSOURCE_VIEW)
    safe_set(view_to_world, "transform_type", unreal.MaterialVectorCoordTransform.TRANSFORM_WORLD)
    connect(light_view_xy, "", view_to_world, "")
    offset_scale = scalar(shadow, "BangShadowOffset", -1.15, -400, 320)
    lateral_offset = expression(shadow, unreal.MaterialExpressionMultiply, -180, 160)
    connect(view_to_world, "", lateral_offset, "A")
    connect(offset_scale, "", lateral_offset, "B")
    shadow_camera_position = expression(shadow, unreal.MaterialExpressionCameraPositionWS, -620, 440)
    shadow_world_position = expression(shadow, unreal.MaterialExpressionWorldPosition, -620, 540)
    shadow_view_delta = expression(shadow, unreal.MaterialExpressionSubtract, -400, 460)
    connect(shadow_camera_position, "", shadow_view_delta, "A")
    connect(shadow_world_position, "", shadow_view_delta, "B")
    shadow_camera = expression(shadow, unreal.MaterialExpressionNormalize, -180, 440)
    connect(shadow_view_delta, "", shadow_camera, "VectorInput")
    depth_bias = scalar(shadow, "BangShadowDepthBias", -0.65, -180, 520)
    depth_offset = expression(shadow, unreal.MaterialExpressionMultiply, 40, 440)
    connect(shadow_camera, "", depth_offset, "A")
    connect(depth_bias, "", depth_offset, "B")
    total_offset = expression(shadow, unreal.MaterialExpressionAdd, 260, 240)
    connect(lateral_offset, "", total_offset, "A")
    connect(depth_offset, "", total_offset, "B")
    connect_property(total_offset, "", unreal.MaterialProperty.MP_WORLD_POSITION_OFFSET)
    face_stencil = stencil_equal(shadow, 1.0, -1500, 760)
    shadow_strength = scalar(shadow, "BangShadowStrength", 0.22, -180, 920)
    shadow_alpha_a = expression(shadow, unreal.MaterialExpressionMultiply, 40, 780)
    connect(shadow_base, "A", shadow_alpha_a, "A")
    connect(face_stencil, "", shadow_alpha_a, "B")
    shadow_alpha = expression(shadow, unreal.MaterialExpressionMultiply, 260, 780)
    connect(shadow_alpha_a, "", shadow_alpha, "A")
    connect(shadow_strength, "", shadow_alpha, "B")
    connect_property(shadow_alpha, "", unreal.MaterialProperty.MP_OPACITY)
    shadow_color = vector(shadow, "BangShadowColor", (0.20, 0.07, 0.075, 1.0), 40, 1040)
    connect_property(shadow_color, "RGB", unreal.MaterialProperty.MP_EMISSIVE_COLOR)
    unreal.MaterialEditingLibrary.recompile_material(shadow)
    unreal.EditorAssetLibrary.save_loaded_asset(shadow)
    return invisible, shadow, overlay
